### ISSUE TITLE
Remove this line script(src='/js/main.js') from your layout

### ISSUE THREAD

**Issue by slidenerd** [niallobrien/hackathon-starter-plus#6]
It throws a 404 in the network tab
![screen shot 2018-12-19 at 11 46 53 am](https://user-images.githubusercontent.com/5139030/50202338-cf98af80-0383-11e9-8dbd-de0dcdbb3875.png)
Not sure if it is something only I am seeing on my end though

Also you might want to remove popper js completely and add bootstrap.bundle.min.js instead

Are these lines needed?
 script(src='/js/lib/jquery.min.js')
    script(src='/js/lib/bootstrap.min.js')
    script(src='/js/lib/popper.min.js')
script(src='/js/main.js')
we are linking the libs in the bundle no?

Also assuming these are not needed
app.use('/js/lib', express.static(path.join(__dirname, 'node_modules/popper.js/dist/umd'), { maxAge: 31557600000 }));
app.use('/js/lib', express.static(path.join(__dirname, 'node_modules/bootstrap/dist/js'), { maxAge: 31557600000 }));
app.use('/js/lib', express.static(path.join(__dirname, 'node_modules/jquery/dist'), { maxAge: 31557600000 }));
app.use('/webfonts', express.static(path.join(__dirname, 'node_modules/@fortawesome/fontawesome-free/webfonts'), { maxAge: 31557600000 }));

**Comment by niallobrien** [comment]
Did you run npm run watch in another terminal before starting the server?

Is the Bootstrap bundle available within the npm package? I'm on mobile atm but will need to check.

Regarding the app.use() lines, I will take a look. They must have been added to the project after I setup the asset pipeline.

**Comment by slidenerd** [comment]
I think I figured it out, need to unlink to all those scripts and include only the final one generated out of webpack dist, somehow I did not see that, also I dont recommend purgecss in the production asset pipeline, try adding bootstrap to it and it breaks the modal styles in dev vs prod. You need to maintain an explicit whitelist to keep track of classes to not purge and I think that will be a sure shot highway to bugs especially when JS is modifying many of these bootstrap elements and adding classes dynamically. For example the modals break because d-block show and fade classes are purged which are added only dynamically
